server:
  port: 8083

spring:
  data:
    mongodb:
      host: "mongo"
      port: "27017"
      database: "store"
      authentication-database: "admin"
      username: "root"
      password: "example"