server:
  port: 8083

spring:
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "store"
      authentication-database: "admin"
      username: "root"
      password: "example"

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
